version: '3.1'

services: 
  shippy-consignment-cli:
    build: ./consignment-cli
  
  shippy-consignment-service:
    build: ./consignment-service
    ports: 
      - 50051:50051
    environment: 
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"
  
  shippy-vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment: 
      MICRO_ADDRESS: ":50051"